### ISSUE TITLE
Overlapping content 

### ISSUE THREAD

**Issue by MhtSuthar** [thewaychung/ExpandableGridView#1]
Hi, 
when i extent gridview column size to 7 than collapse some data, i dont know how to resolve?
![screenshot_2015-12-19-17-33-49](https://cloud.githubusercontent.com/assets/7448975/11912893/80979124-a677-11e5-8801-6b188692584e.png)

**Comment by thewaychung** [comment]
Sorry for replying late. For your issue, I think the reason is that the **GridView** has not set **background color**. 

The mechanism of the expand/split GridView is: 
1. Get the drawing of the GridView, which will create a bitmap;
2. Split the bitmap into two part at the touch position;
3. Inject a new layout, which is a new GridView here, in the middle of the two bitmap;
4. Add the two bitmap and the middle layout to a new cover view, bring the cover view to front to cover the origin GridView;

By doing these steps, we create the expand/split effect.
The GridView's background color is transparent by default. So it would collapse at the bottom part.

The solution is set background color to the GridView.
